--Crear La Base de DAtos

-- DROP DATABASE IMBD_DB;

CREATE DATABASE IMBD_DB

--COLOCAR LA BD EN USO PARA PODER REALIZAR EL RESTO DE PROCEDIMIENTOS

USE IMBD_DB;

-- DROP SCHEMA dbo;

CREATE SCHEMA dbo;
-- IMDB.dbo.Genre definition

-- Drop table

-- DROP TABLE IMDB.dbo.Genre;

CREATE TABLE IMDB.dbo.Genre (
	id bigint IDENTITY(0,1) NOT NULL,
	name varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);