version: "3.7"
services:
    sql-server:
        container_name: sql-server-netflix
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:  
            - "1433:1433"
        environment:
            ACCEPT_EULA: "Y" 
            SA_PASSWORD: "Netflix-2021"
            MSSQL_PID: "Enterprise"