version: "3.7"
services:
    sql-server1:
        container_name: sql-server-imdb
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:  
            - "1433:1433"
        environment:
            ACCEPT_EULA: "Y" 
            SA_PASSWORD: "Imdb-2021"
        networks:
            lanbases:
                ipv4_address: 192.168.1.2
    sql-server2:
        container_name: sql-server-netflix
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:  
            - "1466:1466"
        environment:
            ACCEPT_EULA: "Y" 
            SA_PASSWORD: "Netflix-2021"
        networks:
            lanbases:
                ipv4_address: 192.168.1.3
networks:
    lanbases:
        driver: macvlan
        driver_opts: 
            parent: eth0
        ipam: 
            config:
                - subnet: "192.168.1.0/24"
                  gateway: "192.168.1.1"



             
